export const CHANGE_DELIVERY_FILTER = 'CHANGE_DELIVERY_FILTER'

export const FETCH_DELIVERY_LIST_REQU = 'FETCH_DELIVERY_LIST_REQU'
export const FETCH_DELIVERY_LIST_SUCC = 'FETCH_DELIVERY_LIST_SUCC'
export const FETCH_DELIVERY_LIST_FAIL = 'FETCH_DELIVERY_LIST_FAIL'

export const SORT_DELIVERY_LIST = 'SORT_DELIVERY_LIST'

export const RESET_DELIVERY_ITEM_STATUS = 'RESET_DELIVERY_ITEM_STATUS'

export const FETCH_DELIVERY_ITEM_STATUS_REQU = 'FETCH_DELIVERY_ITEM_STATUS_REQU'
export const FETCH_DELIVERY_ITEM_STATUS_SUCC = 'FETCH_DELIVERY_ITEM_STATUS_SUCC'
export const FETCH_DELIVERY_ITEM_STATUS_FAIL = 'FETCH_DELIVERY_ITEM_STATUS_FAIL'

export const FETCH_CONTRACT_REQU = 'FETCH_CONTRACT_REQU'
export const FETCH_CONTRACT_SUCC = 'FETCH_CONTRACT_SUCC'
export const FETCH_CONTRACT_FAIL = 'FETCH_CONTRACT_FAIL'

export const FETCH_DELIVERY_COMMENTS_REQU = 'FETCH_DELIVERY_COMMENTS_REQU'
export const FETCH_DELIVERY_COMMENTS_SUCC = 'FETCH_DELIVERY_COMMENTS_SUCC'
export const FETCH_DELIVERY_COMMENTS_FAIL = 'FETCH_DELIVERY_COMMENTS_FAIL'

export const CHANGE_NEW_DELIVERY_COMMENT = 'CHANGE_NEW_DELIVERY_COMMENT'

export const SAVE_DELIVERY_COMMENT_REQU = 'SAVE_DELIVERY_COMMENT_REQU'
export const SAVE_DELIVERY_COMMENT_SUCC = 'SAVE_DELIVERY_COMMENT_SUCC'
export const SAVE_DELIVERY_COMMENT_FAIL = 'SAVE_DELIVERY_COMMENT_FAIL'

export const FETCH_PERQUISITES_REQU = 'FETCH_PERQUISITES_REQU'
export const FETCH_PERQUISITES_SUCC = 'FETCH_PERQUISITES_SUCC'
export const FETCH_PERQUISITES_FAIL = 'FETCH_PERQUISITES_FAIL'

export const FETCH_PAYMENTPLAN_REQU = 'FETCH_PAYMENTPLAN_REQU'
export const FETCH_PAYMENTPLAN_SUCC = 'FETCH_PAYMENTPLAN_SUCC'
export const FETCH_PAYMENTPLAN_FAIL = 'FETCH_PAYMENTPLAN_FAIL'

export const FETCH_PAYMENTS_REQU = 'FETCH_PAYMENTS_REQU'
export const FETCH_PAYMENTS_SUCC = 'FETCH_PAYMENTS_SUCC'
export const FETCH_PAYMENTS_FAIL = 'FETCH_PAYMENTS_FAIL'

export const FETCH_REGISTRATION_REQU = 'FETCH_REGISTRATION_REQU'
export const FETCH_REGISTRATION_SUCC = 'FETCH_REGISTRATION_SUCC'
export const FETCH_REGISTRATION_FAIL = 'FETCH_REGISTRATION_FAIL'

export const SAVE_REGISTRATION_REQU = 'SAVE_REGISTRATION_REQU'
export const SAVE_REGISTRATION_SUCC = 'SAVE_REGISTRATION_SUCC'
export const SAVE_REGISTRATION_FAIL = 'SAVE_REGISTRATION_FAIL'

export const SET_REGISTRATION_DATA = 'SET_REGISTRATION_DATA'

export const SAVE_DELIVERY_DATA_REQU = 'SAVE_DELIVERY_DATA_REQU'
export const SAVE_DELIVERY_DATA_SUCC = 'SAVE_DELIVERY_DATA_SUCC'
export const SAVE_DELIVERY_DATA_FAIL = 'SAVE_DELIVERY_DATA_FAIL'

export const SET_DELIVERY_DATE_ARRANGED = 'SET_DELIVERY_DATE_ARRANGED'
export const SET_DELIVERY_TIME_ARRANGED = 'SET_DELIVERY_TIME_ARRANGED'
export const SET_DELIVERED = 'SET_DELIVERED'

export const SAVE_CONTRACT_REQU = 'SAVE_CONTRACT_REQU'
export const SAVE_CONTRACT_SUCC = 'SAVE_CONTRACT_SUCC'
export const SAVE_CONTRACT_FAIL = 'SAVE_CONTRACT_FAIL'

export const MOVE_CCVEHICLE_EDITINGPLUS_REQU = 'MOVE_CCVEHICLE_EDITINGPLUS_REQU'
export const MOVE_CCVEHICLE_EDITINGPLUS_SUCC = 'MOVE_CCVEHICLE_EDITINGPLUS_SUCC'
export const MOVE_CCVEHICLE_EDITINGPLUS_FAIL = 'MOVE_CCVEHICLE_EDITINGPLUS_FAIL'

export const MOVE_CCVEHICLE_INSALE_REQU = 'MOVE_CCVEHICLE_INSALE_REQU'
export const MOVE_CCVEHICLE_INSALE_SUCC = 'MOVE_CCVEHICLE_INSALE_SUCC'
export const MOVE_CCVEHICLE_INSALE_FAIL = 'MOVE_CCVEHICLE_INSALE_FAIL'

export const MOVE_CCVEHICLE_SOLD_REQU = 'MOVE_CCVEHICLE_SOLD_REQU'
export const MOVE_CCVEHICLE_SOLD_SUCC = 'MOVE_CCVEHICLE_SOLD_SUCC'
export const MOVE_CCVEHICLE_SOLD_FAIL = 'MOVE_CCVEHICLE_SOLD_FAIL'

export const FETCH_TASKS_REQU = 'FETCH_TASKS_REQU'
export const FETCH_TASKS_SUCC = 'FETCH_TASKS_SUCC'
export const FETCH_TASKS_FAIL = 'FETCH_TASKS_FAIL'

export const ADD_TASK_REQU = 'ADD_TASK_REQU'
export const ADD_TASK_SUCC = 'ADD_TASK_SUCC'
export const ADD_TASK_FAIL = 'ADD_TASK_FAIL'

export const SAVE_TASK_REQU = 'SAVE_TASK_REQU'
export const SAVE_TASK_SUCC = 'SAVE_TASK_SUCC'
export const SAVE_TASK_FAIL = 'SAVE_TASK_FAIL'

export const REMOVE_TASK_REQU = 'REMOVE_TASK_REQU'
export const REMOVE_TASK_SUCC = 'REMOVE_TASK_SUCC'
export const REMOVE_TASK_FAIL = 'REMOVE_TASK_FAIL'

export const FETCH_OPENPAYMENTS_REQU = 'FETCH_OPENPAYMENTS_REQU'
export const FETCH_OPENPAYMENTS_SUCC = 'FETCH_OPENPAYMENTS_SUCC'
export const FETCH_OPENPAYMENTS_FAIL = 'FETCH_OPENPAYMENTS_FAIL'

export const FETCH_CONTRACTDOCS_REQU = 'FETCH_CONTRACTDOCS_REQU'
export const FETCH_CONTRACTDOCS_SUCC = 'FETCH_CONTRACTDOCS_SUCC'
export const FETCH_CONTRACTDOCS_FAIL = 'FETCH_CONTRACTDOCS_FAIL'

export const SAVE_CONTRACTDOC_REQU = 'SAVE_CONTRACTDOC_REQU'
export const SAVE_CONTRACTDOC_SUCC = 'SAVE_CONTRACTDOC_SUCC'
export const SAVE_CONTRACTDOC_FAIL = 'SAVE_CONTRACTDOC_FAIL'

export const SHOW_DIALOG = 'SHOW_DIALOG'
export const HIDE_DIALOG = 'HIDE_DIALOG'

export const SHOW_DIALOG_EXT = 'SHOW_DIALOG_EXT'
export const HIDE_DIALOG_EXT = 'HIDE_DIALOG_EXT'

export const FETCH_TRADEIN_REQU = 'FETCH_TRADEIN_REQU'
export const FETCH_TRADEIN_SUCC = 'FETCH_TRADEIN_SUCC'
export const FETCH_TRADEIN_FAIL = 'FETCH_TRADEIN_FAIL'

export const FETCH_TRADEINCAR_REQU = 'FETCH_TRADEINCAR_REQU'
export const FETCH_TRADEINCAR_SUCC = 'FETCH_TRADEINCAR_SUCC'
export const FETCH_TRADEINCAR_FAIL = 'FETCH_TRADEINCAR_FAIL'

export const SAVE_TRADEINCAR_REQU = 'SAVE_TRADEINCAR_REQU'
export const SAVE_TRADEINCAR_SUCC = 'SAVE_TRADEINCAR_SUCC'
export const SAVE_TRADEINCAR_FAIL = 'SAVE_TRADEINCAR_FAIL'

export const SET_TRADEINCAR_DATA = 'SET_TRADEINCAR_DATA'